import Head from 'next/head'
import React from 'react'
import { Layout } from "antd"
import Navbar from "@/components/Navbar"
import styles from "@/styles/Home.module.scss"
import LoginPage from '@/components/LoginPage'
import { Usercontext } from '@/contexts/user'

export default function Home() {
  const {user} = React.useContext(Usercontext)
  console.log(user)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Layout.Header>
          <Navbar />
        </Layout.Header>
        <Layout.Content className={styles.main}>
          { user ?
           "hi" 
           :
          
          <LoginPage />
          }
        </Layout.Content>
      </Layout>
    </>
  )
}
